"""Phase 7 (v2) · Section 1 · Your Mind Is the Market. Lessons 1-13.
She already knows the chart. The chart isn't the lesson anymore. She is."""
from v2lib import *  # noqa: F401,F403
from v2tapes import *  # noqa: F401,F403
from p7lib import lesson, dayli, reflect, write, chk, qq, o, mono, split, col, tally, xchart, PIL, P

S = 's18'
L = {}
H1 = {'tf': '1M', 'label': 'MNQ'}
IN_TRADE = lambda bars, e_at, **kw: dict(pil=None, lines=trade_lines(e_at), head={'tf': '1M', 'label': 'Long 2 MNQ'}, **kw)

# ── 1 · The Moment Between ────────────────────────────────────────────
L[1] = lesson(P, S, 1, 'The Moment Between', 'You know the model. So why do you still break it?',
  'Notice the gap between seeing the chart and clicking, and learn the PAUSE that lives there.',
  'Did price change, or did my emotion change?', [
    scene('Phase 7 · The Mindset Behind the Model', '', [
        say('You can read structure.', 'You can find the PIL.', 'You can wait for the close, take the retest, size the trade, place the stop.'),
        say('So here’s a question nobody asks in Phases 1 through 6:'),
        say('<b>If you know all of that… why do you still break your own rules?</b>', big=True),
        ch(LOSS, play=(LM['indication'] - 2, LM['retest'] + 4), head={'tf': '1M', 'label': 'You’re in a valid long'}, lines=trade_lines(LM['retest'], entry=LOSS_E, stop=LOSS_E - 30, target=LOSS_E + 60), pil=None),
        say('Valid setup. First retest. You’re in. Stop −30. Target +60.', 'Price pulls back a little.'),
        th('“I don’t like this candle.”', '“What if it turns?”', '“Maybe I should just get out.”'),
        say('Look at what just happened.', 'The chart printed one red candle.', '<b>Your plan didn’t change. Something in you did.</b>'),
        {'clear': True},
        say('That space between what you <em>see</em> and what you <em>do</em>?', 'That’s where every trade in Phase 7 is decided.', big=False),
        {'reveal': True, 'say': ['<b>PHASES 1–6 TAUGHT YOU HOW TO READ THE MARKET.</b>', '<b>PHASE 7 TEACHES YOU HOW TO READ YOURSELF WHILE YOU’RE READING IT.</b>']},
        cards('FEEL', 'NOTICE', 'NAME IT', 'CHECK THE RULE', 'CHOOSE THE BEHAVIOR'),
        pr('YOU DON’T HAVE TO CONTROL EVERY FEELING. YOU HAVE TO CONTROL WHAT THE FEELING GETS PERMISSION TO CHANGE.'),
    ], cta='Start →'),
    {'type': 'p7_pause', 'kicker': 'Your new button', 'title': '⏸ PAUSE',
     'facts': [['Trade', 'Long 2 MNQ'], ['Plan', 'SL −30 · TP +60'], ['Management rule', 'None triggered']],
     'chart': xchart(FEAR, show=FEAR_CP + 1, pil=None, lines=trade_lines(FEAR_E), head={'tf': '1M', 'label': 'In the trade'}), 'thought': '“I don’t like this candle.”', 'action': 'Move my stop closer',
     'pause': {'market': 'A normal pullback. Nothing structural changed.', 'plan': 'No management rule triggered. Hold to SL / TP.', 'mind': 'Nervous. I want the discomfort to stop.', 'action': 'Nothing needs to change.'},
     'asks': [qq('DID PRICE CHANGE… OR DID MY EMOTION CHANGE?', o('Price changed', feedback='Price did a normal pullback your plan already expected.'), o('My emotion changed', True, why='Which means the decision doesn’t have to.'), recog=True)],
     'punch': 'MARKET · PLAN · MIND · ACTION. This button lives in every simulator from here on.'},
    dayli('Fear doesn’t have to leave the room. <em>It just doesn’t get to hold the mouse.</em>'),
    reflect('Think of a time you broke a rule you knew. What were you feeling right before you clicked?',
            'I knew the rule. Right before I clicked I felt something (rushed, scared, excited) and the feeling made the decision instead of the plan.'),
  ], ['Feel it. Notice it. Name it.', 'Check the rule before you act.', 'Did price change, or did I?'],
  'YOU DON’T HAVE TO CONTROL EVERY FEELING. YOU HAVE TO CONTROL WHAT IT GETS TO CHANGE.', 85)
# the reveal beat is just a big say
L[1]['slides'][0]['beats'][9] = say('<b>PHASES 1–6 TAUGHT YOU HOW TO READ THE MARKET.</b>', '<b>PHASE 7 TEACHES YOU HOW TO READ YOURSELF WHILE YOU’RE READING IT.</b>')

# ── 2 · After the Win ─────────────────────────────────────────────────
L[2] = lesson(P, S, 2, 'After the Win', 'Why your best trade can become the reason you take your worst one.',
  'Feel what a clean win does to your judgment, and learn why confidence is not confirmation.',
  'Did the market give me a setup, or did the win give me permission?', [
    scene('After the Win', 'You just hit TP.', [
        ch(WIN, play=(WIN_E, len(WIN)), **IN_TRADE(WIN, WIN_E)),
        say('Clean entry. Clean execution.', '<b>You followed your plan perfectly.</b> +2R.'),
        say('Then you look back at the chart.', 'Price is still moving.'),
        th('“I’m locked in today.”', '“I could probably catch one more.”', '“I’m seeing the market so clearly.”'),
        say('Nothing about the market changed.', '<b>But something changed in you.</b>'),
        ch(MESS, head={'tf': '1M', 'label': 'The next chart'}, caption='Price wicked through the PIL. It never closed through it.'),
        say('There is no valid setup here. Your model is clear about that.', 'You <em>know</em> there’s no trade.', '<b>So why do you suddenly want one?</b>'),
        th('“It’s basically the same move.”', '“I’m on today.”'),
        choice('Your cursor is over BUY. What do you do?',
            op('Take it. You’re on.', track=['greedDrivenDecisionCount', 'emotionalTradesTaken'],
               chart=ch(MESS_FAIL, play=(len(MESS), len(MESS_FAIL)), head={'tf': '1M', 'label': 'You bought the wick'}, tags=[{'at': len(MESS_FAIL) - 1, 'text': '−1R', 'tone': 'warn'}]),
               say=['It never closed through. It never had to.', 'The win didn’t change the chart. It changed how much you trusted yourself.', 'And if it had worked? <b>You’d have learned the wrong lesson faster.</b>'],
               tally=[['TRADE 1', '+2R ✓ PLAN'], ['TRADE 2', '−1R · NO SETUP', 'mind'], ['DAY', '+1R', 'neutral']]),
            op('Wait for a real close through the PIL', track='ruleBasedResponses',
               chart=ch(MESS_WAIT, play=(len(MESS), len(MESS_WAIT)), head={'tf': '1M', 'label': 'You waited'}),
               say=['It never closed through.', 'No setup ever formed. Nothing for your model to do.'], tally=[['DAY', '+2R', 'ok'], ['RULES BROKEN', '0', 'ok']]),
            op('Close the platform. The plan said done after +2R.', track='ruleBasedResponses',
               say=['You logged the trade, wrote one line in your journal, and closed the chart.', 'Maybe it moved after. You’ll never know. <b>That’s fine.</b>'],
               tally=[['DAY', '+2R', 'ok'], ['SESSION', 'COMPLETE ✓', 'big']])),
        say('<b>The first win gave you permission you never actually had.</b>'),
        who('THE TRADER', ['She waited.', 'She followed confirmation.', 'She executed her model.'],
            'THE FEELING', ['She feels sharp.', 'Confident.', 'Maybe even invincible.'], title='WHO’S TRADING NOW?', verdict='Before the win, the trader. After the win, the feeling.'),
        pr('CONFIDENCE IS NOT CONFIRMATION.'),
    ]),
    split('Not every runner is greed', 'Same position. Different source.', col('PLANNED RUNNER', ['Written before entry.', 'Trail rule defined.', 'Follows the plan.'], 'ok'),
          col('EXCITEMENT RUNNER', ['Added at the target.', '“It looks so bullish.”', 'The plan, rewritten by a feeling.'], 'mind'), verdict='Ask: was it in the plan, or did excitement add it?'),
    dayli('Enough is a number you decide <em>before</em> the trade feels amazing.'),
    reflect('What does a win do to you? What do you want to do right after one?',
            'After a win I feel sharp and want one more, or a bigger size, or a farther target. The win didn’t give me a setup. Confidence is not confirmation.'),
  ], ['A win changes you, not the chart.', 'Greed is refusing to respect “enough”.', 'Confidence is not confirmation.'],
  'CONFIDENCE IS NOT CONFIRMATION.', 85)

# ── 3 · On a Heater ───────────────────────────────────────────────────
L[3] = lesson(P, S, 3, 'On a Heater', 'Four green days. Your journal looks incredible.',
  'Feel a winning streak push your size up, and keep your risk where your calm self put it.',
  'Did my risk plan change, or did my streak?', [
    scene('On a Heater', 'Monday to Thursday', [
        cards('MON · +2R ✓', 'TUE · +1R ✓', 'WED · +2R ✓', 'THU · +1.5R ✓'),
        say('Four green days in a row.', 'Every trade by the plan. Your journal looks incredible.'),
        th('“I’ve figured this out.”', '“My size is too small for how good I am.”', '“Let’s go bigger today.”'),
        say('Friday. A valid setup. Your plan says <b>2 contracts</b>.', 'Your cursor is on <b>4</b>.'),
        ch(HES, show=HM['retest'] + 1, head={'tf': '1M', 'label': 'Friday · first retest'}),
        choice('How many?',
            op('4 contracts. You’ve earned it.', track=['overconfidenceCount', 'emotionalTradesTaken'],
               chart=ch(LOSS, play=(LM['retest'] + 1, len(LOSS)), head={'tf': '1M', 'label': 'Same model. Different day.'}, tags=[{'at': len(LOSS) - 1, 'text': 'STOP', 'tone': 'warn'}]),
               say=['It was valid. It lost. That happens.', 'At double size, one valid loss took <b>2R</b> instead of 1.'],
               tally=[['THIS TRADE', '−2R', 'mind'], ['THE WEEK', '+6.5R → +4.5R', 'neutral'], ['RULES BROKEN', '1 · size', 'mind']]),
            op('4 contracts (and this time it wins)', track=['overconfidenceCount'],
               chart=ch(HES, play=(HM['retest'] + 1, len(HES)), head={'tf': '1M', 'label': 'It worked'}),
               say=['+4R. It worked.', '<b>This is the dangerous version.</b>', 'Now 4 feels normal. Your size grew. Your rules never did.']),
            op('2 contracts. The plan.', track='ruleBasedResponses',
               chart=ch(LOSS, play=(LM['retest'] + 1, len(LOSS)), head={'tf': '1M', 'label': 'Same model. Different day.'}),
               say=['Valid loss. −1R.', 'Still +5.5R for the week. Monday you’ll trade the same size again.'],
               tally=[['THIS TRADE', '−1R', 'neutral'], ['THE WEEK', '+5.5R', 'ok'], ['RULES BROKEN', '0', 'ok']])),
        who('THE TRADER', ['Sizes from her risk plan.', 'Wrote it when she was calm.'],
            'THE STREAK', ['Sizes from the last four days.', 'Calls it “earned”.']),
        pr('A STREAK IS A RESULT. IT ISN’T A NEW RISK PLAN.'),
    ]),
    {'type': 'p7_baseline', 'kicker': 'Your baseline card', 'title': 'Written before the streak',
     'baseline': [['Risk', '1R'], ['Max trades', '2'], ['Entry rules', 'Unchanged'], ['Management', 'Unchanged']],
     'runs': [{'label': '5 WINS', 'seq': 'WWWWW', 'thoughts': ['“I can’t miss.”', '“Triple size?”'],
               'ask': qq('DID RISK DISAPPEAR?', o('Yes, triple it', feedback='Your confidence changed. Did your risk plan?', track='overconfidenceCount'), o('NO', True, why='Same risk. Same baseline. Wins don’t make the next trade safer.'))}],
     'punch': 'If size should grow, it grows in review, with evidence. Not on a Friday because Thursday felt good.'},
    dayli('Trade like the version of you who wrote the plan. <em>Not the version who just read her P&amp;L.</em>'),
    reflect('What changes in you during a winning streak?',
            'I feel like I can’t miss, so I want to size up or loosen my rules. If it works, the habit gets rewarded. My risk plan didn’t change because I won.'),
  ], ['A streak changes how you feel, not your risk.', 'The dangerous version is when it works.', 'Size changes in review, not on a heater.'],
  'A STREAK IS A RESULT. IT ISN’T A NEW RISK PLAN.', 85)

# ── 4 · After the Loss ────────────────────────────────────────────────
L[4] = lesson(P, S, 4, 'After the Loss', 'The market didn’t take anything from you.',
  'Feel a valid loss turn into urgency, and catch the revenge trade before it catches you.',
  'Would I take this exact trade if the last one never happened?', [
    scene('After the Loss', '9:52', [
        ch(LOSS, play=(LM['indication'] - 2, len(LOSS)), head={'tf': '1M', 'label': 'A valid setup'}, tags=[{'at': LM['retest'], 'text': 'YOU’RE IN', 'tone': 'gold'}, {'at': len(LOSS) - 1, 'text': '−1R', 'tone': 'warn'}]),
        say('Valid setup. You took it at the first retest. Stopped out.', '<b>You did everything right. And the market still said no.</b>'),
        th('“That shouldn’t have stopped me.”', '“I need that back.”', '“Okay. Next one.”'),
        ch(INC, head={'tf': '1M', 'label': 'Two minutes later'}, caption='Indication. No Correction. No Continuation. But it’s moving.'),
        say('If you’d never taken the last trade, would this chart even be interesting?'),
        choice('What do you do?',
            op('Get in now. Make it back.', track=['revengeDecisionCount', 'emotionalTradesTaken'],
               chart=ch(INC_FAIL, play=(INC_AT, len(INC_FAIL)), head={'tf': '1M', 'label': 'You got in'}, tags=[{'at': len(INC_FAIL) - 1, 'text': '−1R', 'tone': 'warn'}]),
               say=['Two losses. One was the market. <b>One was the last trade.</b>'], tally=[['TRADE 1', '−1R · valid', 'neutral'], ['TRADE 2', '−1R · revenge', 'mind'], ['DAY', '−2R', 'neutral']]),
            op('Get in now, double size. Faster.', track=['revengeDecisionCount', 'emotionalTradesTaken'],
               chart=ch(INC_FAIL, play=(INC_AT, len(INC_FAIL)), head={'tf': '1M', 'label': 'Double size'}, tags=[{'at': len(INC_FAIL) - 1, 'text': '−2R', 'tone': 'warn'}]),
               say=['This is how −1R becomes −3R.', 'Not one bad trade. <b>One bad decision about the last one.</b>'], tally=[['DAY', '−3R', 'mind'], ['RULES BROKEN', '2 · entry + size', 'mind']]),
            op('Wait. The model isn’t complete.', track='revengeAvoided',
               chart=ch(INC_WAIT, play=(INC_AT, len(INC_WAIT)), head={'tf': '1M', 'label': 'You waited'}),
               say=['It never completed.', 'Your day is still −1R. A valid loss. <b>That’s the whole damage.</b>'], tally=[['DAY', '−1R · valid', 'neutral'], ['RULES BROKEN', '0', 'ok']])),
        who('THE TRADER', ['Took a valid trade.', 'Accepted a valid loss.'], 'THE WOUND', ['Wants the market to give it back.', 'Right now.']),
        say('<b>Would you take this exact trade if the previous trade never happened?</b>', 'If the answer is no, the last trade is still trading you.'),
        pr('THE MARKET DIDN’T TAKE ANYTHING FROM YOU. SO WHAT ARE YOU TRYING TO GET BACK?'),
    ]),
    {'type': 'p7_loop', 'kicker': 'The revenge loop', 'title': 'It keeps going around',
     'nodes': ['LOSS', 'FRUSTRATION', 'URGENCY', 'LOWER STANDARDS', 'BIGGER SIZE / FAST ENTRY', 'MORE DAMAGE', 'MORE URGENCY'],
     'center': 'The next trade becomes about the last one.',
     'asks': [qq('WHERE DOES IT BREAK MOST EASILY?', o('After more damage', feedback='It can. By then the day is expensive.'), o('Between URGENCY and LOWER STANDARDS', True, why='Notice the urgency. Check the rule before the standards drop.'))]},
    dayli('Revenge feels like action. <em>It’s really the last trade still trading you.</em>'),
    reflect('How do you know when you’re trading to get something back?',
            'When I wouldn’t take this exact setup if the last trade never happened. Urgency, lower standards and bigger size are the signs. A valid loss is logged, not avenged.'),
  ], ['A valid loss isn’t a debt.', 'Ask: would I take this if the last trade never happened?', 'Urgency is the tell.'],
  'THE MARKET DIDN’T TAKE ANYTHING FROM YOU.', 85)

# ── 5 · Three in a Row ────────────────────────────────────────────────
L[5] = lesson(P, S, 5, 'Three in a Row', 'When losing starts to feel like who you are.',
  'Feel a losing streak shake your trust, and keep judging the model slowly and the next setup on its own.',
  'Did my model stop working, or did my confidence?', [
    scene('Three in a Row', 'Tuesday, Wednesday, Thursday', [
        cards('TUE · valid · −1R', 'WED · valid · −1R', 'THU · valid · −1R'),
        say('Three trades. Three losses.', 'Every one by the plan.'),
        th('“Maybe the model doesn’t work.”', '“Maybe I’m not cut out for this.”', '“I’ll wait for a REALLY perfect one.”'),
        ch(HES, play=(HM['indication'] - 2, HM['retest'] + 1), head={'tf': '1M', 'label': 'Friday'}),
        say('Indication. Correction. Continuation. First retest.', '<b>Your model, start to finish.</b>'),
        choice('Your hand is shaking a little. What do you do?',
            op('Skip it. You can’t take another loss.', track='hesitationCount',
               chart=ch(HES, play=(HM['retest'] + 1, len(HES)), head={'tf': '1M', 'label': 'Without you'}),
               say=['It worked.', 'Without you.', 'And now the next one is harder, because you’ve added “I missed it” to “I keep losing”.']),
            op('Take it at half size. Just to be safe.', track='hesitationCount',
               chart=ch(HES, play=(HM['retest'] + 1, len(HES)), head={'tf': '1M', 'label': 'Half size'}),
               say=['+1R instead of +2R.', 'The streak didn’t just change your mood. <b>It quietly rewrote your risk plan.</b>']),
            op('Take it. Standard size.', track='ruleBasedResponses',
               chart=ch(HES, play=(HM['retest'] + 1, len(HES)), head={'tf': '1M', 'label': 'Standard size'}),
               say=['+2R.', 'And if it had lost? Four in a row. Still the right decision.', '<b>Losing streaks happen inside working models.</b> Three trades can’t tell you which one you have.'])),
        who('THE TRADER', ['Judges each setup on its own.', 'Judges the model over many trades.'],
            'THE STREAK', ['Wants proof before it trusts you again.', 'Treats three trades like a verdict.']),
        pr('A LOSING STREAK CHANGES HOW YOU FEEL ABOUT THE MODEL. IT DOESN’T CHANGE THE MODEL.'),
    ]),
    {'type': 'p7_loop', 'kicker': 'The confidence loop', 'title': 'Watch it spin',
     'nodes': ['LOSS', 'DOUBT THE MODEL', 'SKIP A VALID SETUP', 'IT WINS', 'FOMO', 'CHASE THE NEXT', 'LOSS', 'MORE DOUBT'], 'breakAt': 2, 'step': 0.6,
     'center': 'Confidence borrowed from the last trade.',
     'asks': [qq('WHAT STOPS IT AT “SKIP A VALID SETUP”?', o('Waiting until I feel confident', feedback='Feelings follow evidence. They don’t lead it.'), o('Letting the current setup and my rules decide', True, why='Not the streak. The setup and the rules.'))]},
    dayli('Judge your behavior after every trade. <em>Judge the model after a lot of them.</em>'),
    reflect('What do you tell yourself during a losing streak?',
            'That the model stopped working or that I’m not good enough. Three trades can’t answer that. I judge my behavior quickly and the model slowly, over a real sample.'),
  ], ['Losing streaks happen inside working models.', 'Skipping and shrinking are the streak deciding.', 'Judge behavior fast, the model slowly.'],
  'A LOSING STREAK DOESN’T CHANGE THE MODEL.', 85)

# ── 6 · I Knew It ─────────────────────────────────────────────────────
L[6] = lesson(P, S, 6, 'I Knew It', 'You skipped it. It ran without you.',
  'Feel price leave without you and every candle start to look like an entry, and let the move go.',
  'What is FOMO asking me to do right now?', [
    scene('I Knew It', '10:04', [
        ch(FOMO, play=(RM['indication'] - 2, F_25 + 1), head={'tf': '1M', 'label': 'You’re waiting for the retest'}, speed=420),
        say('Indication. Correction. Continuation.', 'You’re waiting for the retest your model requires.', '<b>It never comes back.</b>'),
        th('“I KNEW it.”', '“It’s leaving.”', '“I should’ve just gotten in.”'),
        say('Now every candle feels like an opportunity.'),
        choice('Price is +25 from your level. What do you do?',
            op('Buy now before it’s gone', track=['fomoDecisionCount', 'emotionalTradesTaken'],
               chart=ch(FOMO_REV, play=(F_25 + 1, len(FOMO_REV)), head={'tf': '1M', 'label': 'You chased'}, tags=[{'at': len(FOMO_REV) - 1, 'text': '−1R', 'tone': 'warn'}]),
               say=['It came back to the level you were waiting for. Through your stop.', 'Some days it keeps going instead. <b>That’s how chasing becomes a habit.</b>'],
               tally=[['ENTRY', '+25 above your plan', 'mind'], ['RESULT', '−1R', 'neutral'], ['RULES BROKEN', '1 · chase', 'mind']]),
            op('Let it go', track='fomoRecognized',
               chart=ch(FOMO, play=(F_25 + 1, len(FOMO)), head={'tf': '1M', 'label': 'It ran'}),
               say=['It ran all the way to where your target would have been.', 'Without you.'],
               tally=[['MISSED OPPORTUNITY', '+$500 hypothetical', 'neutral'], ['ACCOUNT CHANGE', '$0', 'ok'], ['RULES BROKEN', '0', 'ok']])),
        say('Missed profit is shown in gray on purpose. It isn’t red. <b>It isn’t a loss.</b>'),
        who('THE TRADER', ['Waited for the retest the model requires.'], 'THE FEAR OF MISSING OUT', ['Sees an entry in every candle.', 'Calls it “I knew it”.']),
        pr('THE MARKET MOVING WITHOUT YOU ISN’T TAKING ANYTHING FROM YOU.'),
    ]),
    {'type': 'p7_seen', 'kicker': 'Your practice history',
     'fallback': {'key': 'chase', 'rule': 'No retest, no chase', 'emotionHint': 'fomo', 'line': 'A very common one: entering after the planned retest is already gone.'}},
    dayli('“I knew it” is the most expensive sentence in trading. 😂 <em>Knowing isn’t the same as an entry.</em>'),
    reflect('What does FOMO make you want to do?',
            'Chase: buy after the retest is gone, invent a new entry, size up to catch up. The market moved without my entry. That’s all.'),
  ], ['“I knew it” isn’t an entry.', 'Missed profit isn’t lost money.', 'Let it go. The next setup is coming.'],
  'MISSED PROFIT IS NOT LOST MONEY.', 85)

# ── 7 · Frozen ────────────────────────────────────────────────────────
L[7] = lesson(P, S, 7, 'Frozen', 'The setup is there. Your finger won’t move.',
  'Feel hesitation after the criteria are complete, and tell it apart from real patience.',
  'Am I waiting for the criteria, or for a guarantee?', [
    scene('Frozen', 'The day after a loss', [
        ch(HES, play=(HM['indication'] - 2, HM['retest'] + 1), head={'tf': '1M', 'label': 'Everything is there'}),
        say('PIL. Indication. Correction. Continuation. First retest.', 'Risk fits. Your rules allow it.', '<b>Every box is checked.</b>'),
        th('“What if I’m wrong again?”', '“Let me see one more candle.”', '“Just a little more confirmation.”'),
        choice('The retest is printing. What do you do?',
            op('Enter on the retest', track='ruleBasedResponses',
               chart=ch(HES, play=(HM['retest'] + 1, len(HES)), head={'tf': '1M', 'label': 'You executed'}),
               say=['+2R. It could have lost. It was still the trade.']),
            op('Wait for one more candle', track='hesitationCount',
               chart=ch(HES, play=(HM['retest'] + 1, HM['retest'] + 5), head={'tf': '1M', 'label': 'One more candle'}),
               say=['Now price is +12 away from your level.', 'The trade you planned is gone. <b>Now you’re deciding whether to chase.</b>', 'One kind of fear just handed you to another.']),
            op('Skip it', track='hesitationCount',
               chart=ch(HES, play=(HM['retest'] + 1, len(HES)), head={'tf': '1M', 'label': 'Without you'}),
               say=['It ran.', 'This one isn’t FOMO. <b>It’s the fear of being wrong, dressed up as caution.</b>'])),
        cards('PATIENCE · waits FOR the criteria', 'HESITATION · waits AFTER them'),
        who('THE TRADER', ['Executes when the criteria complete.'], 'THE FEAR OF BEING WRONG', ['Asks for one more candle.', 'Then one more.']),
        pr('CAUTION ASKS FOR MORE INFORMATION. FEAR ASKS FOR A GUARANTEE.'),
    ]),
    dayli('You don’t need to feel confident to execute. <em>You need the criteria to be complete.</em>'),
    reflect('What’s the difference between patience and hesitation for you?',
            'Patience waits for criteria that aren’t complete yet. Hesitation refuses a setup after the criteria are complete and my rules allow it, usually because of the last trade.'),
  ], ['Patience waits FOR the criteria.', 'Hesitation waits AFTER them.', 'Fear asks for a guarantee. There isn’t one.'],
  'CAUTION ASKS FOR MORE INFORMATION. FEAR ASKS FOR A GUARANTEE.', 85)

# ── 8 · The Candle You Can't Stop Watching ────────────────────────────
L[8] = lesson(P, S, 8, 'The Candle You Can’t Stop Watching', 'When protecting the green costs you the trade.',
  'Feel fear inside a winning trade and separate a planned exit from a frightened one.',
  'Why did I exit: a rule, new information, or fear?', [
    scene('The Candle You Can’t Stop Watching', 'In the trade', [
        ch(FEAR, play=(FEAR_E, FEAR_CP + 1), **IN_TRADE(FEAR, FEAR_E)),
        say('+8. +15. <b>+22.</b> 😌', 'Then a red candle.', 'Your plan: stop −30, target +60. No break-even rule. Nothing has triggered.'),
        th('“I DON’T want this to turn into a loser.”', '“Just lock something in.”'),
        say('You’re not watching the chart anymore. You’re watching your P&amp;L.'),
        choice('What do you do?',
            op('Close it now. Bank the green.', track='fearDrivenManagementCount',
               chart=ch(FEAR, play=(FEAR_CP + 1, len(FEAR)), **IN_TRADE(FEAR, FEAR_E)),
               say=['+10 banked.', 'Then it went to your target. <b>Without you.</b>'], tally=[['YOU KEPT', '+10 pts', 'neutral'], ['YOUR PLAN', '+60 pts', 'ok']]),
            op('Move the stop to break even', track='fearDrivenManagementCount',
               chart=ch(FEAR, play=(FEAR_CP + 1, len(FEAR)), **IN_TRADE(FEAR, FEAR_E), tags=[{'at': FEAR_BE, 'text': 'STOPPED AT BE', 'tone': 'warn'}]),
               say=['The pullback dipped one candle below your entry. Stopped at break even.', 'Then the target. <b>Without you.</b>'], tally=[['YOU KEPT', '$0', 'neutral'], ['YOUR PLAN', '+60 pts', 'ok']]),
            op('Follow the plan', track='ruleBasedResponses',
               chart=ch(FEAR, play=(FEAR_CP + 1, len(FEAR)), **IN_TRADE(FEAR, FEAR_E)),
               say=['Target. +60.', 'Some days the stop gets hit instead. That’s a valid loss, and it still beats a plan you abandon every time a candle scares you.'])),
        say('Taking profit early isn’t automatically wrong.', '<b>The question is: why did you exit?</b>'),
        cards('📐 A MANAGEMENT RULE', '📊 NEW VALID INFORMATION', '😰 FEAR CHANGED THE PLAN'),
        who('THE TRADER', ['Wrote the exit plan while calm.'], 'THE FEAR', ['Wants the discomfort to stop.', 'Will pay the whole target for it.']),
        pr('FEAR WANTS CERTAINTY. TRADING GIVES YOU PROBABILITIES AND RULES.'),
    ]),
    dayli('Stop staring at the P&amp;L. <em>Look at what price is actually doing.</em>'),
    reflect('When do you most want to close a trade early?',
            'When I’m green and a red candle shows up. I ask: is it a management rule, new valid information, or fear? If it’s fear, nothing needs to change.'),
  ], ['Watch price, not your P&L.', 'Ask: why did I exit?', 'Fear wants certainty. There isn’t any.'],
  'FEAR WANTS CERTAINTY. TRADING GIVES YOU PROBABILITIES AND RULES.', 85)

# ── 9 · Just One More ─────────────────────────────────────────────────
L[9] = lesson(P, S, 9, 'Just One More', 'Your day was over. You weren’t ready to be done.',
  'Feel the pull to keep trading after your plan says done, and treat stopping as an execution skill.',
  'Is my trading day over, according to my plan?', [
    scene('Just One More', '10:48', [
        cards('TRADE 1 · −1R', 'TRADE 2 · +2R', 'MAX TRADES · 2 / 2'),
        say('Two trades. Both by the plan. +1R on the day.', 'Your plan says <b>maximum 2</b>. You’re done.'),
        th('“It’s still early.”', '“Just one more.”', '“I’m not ready to be done.”'),
        ch(TINY, play=(TM['indication'] - 2, TM['retest'] + 1), head={'tf': '1M', 'label': 'Something small'}),
        say('Something small and technical forms.'),
        choice('What do you do?',
            op('One more. It’s right there.', track=['overtradeCount', 'emotionalTradesTaken'],
               chart=ch(TINY_FAIL, play=(TM['retest'] + 1, len(TINY_FAIL)), head={'tf': '1M', 'label': 'Trade 3'}, tags=[{'at': len(TINY_FAIL) - 1, 'text': '−1R', 'tone': 'warn'}]),
               say=['A good day became a flat day.', 'And if it had won? Your maximum would mean a little less tomorrow.'],
               tally=[['DAY', '+1R → 0R', 'neutral'], ['RULES BROKEN', '1 · max trades', 'mind']]),
            op('Done. Close the platform.', track='ruleBasedResponses',
               say=['You journal both trades and close the chart.'], tally=[['DAY', '+1R', 'ok'], ['RULES BROKEN', '0', 'ok']], stamp='SESSION COMPLETE ✓'),
            op('Keep watching. Replay mode only.', track='ruleBasedResponses',
               chart=ch(TINY_FAIL, play=(TM['retest'] + 1, len(TINY_FAIL)), head={'tf': '1M', 'label': 'Replay mode'}),
               say=['You watched it fail without paying for it.', 'Studying the market after your day is done is learning. <b>Trading it is not.</b>'])),
        who('THE TRADER', ['Planned two trades.', 'Took two.'], 'THE RESTLESSNESS', ['Wants the feeling of trading.', 'Calls it “one more”.']),
        pr('WHEN YOUR TRADING DAY IS OVER, BEING DONE IS THE EXECUTION.'),
    ]),
    dayli('The third trade always looks like the one that fixes everything. 😂 <em>That’s why the maximum exists.</em>'),
    reflect('What does “one more” usually mean for you?',
            'It means I want the feeling of trading, not that the plan allows a trade. When my max or my daily stop is reached, being done is the execution.'),
  ], ['Your plan defines the end of the day.', '“One more” is a feeling, not a setup.', 'Done is an execution skill.'],
  'WHEN YOUR TRADING DAY IS OVER, BEING DONE IS THE EXECUTION.', 85)

# ── 10 · Waiting Is the Work ──────────────────────────────────────────
WAIT_CLOCK = {'start': '9:45', 'step': 3, 'from': 0}
L[10] = lesson(P, S, 10, 'Waiting Is the Work', 'Nothing yet. That’s not nothing.',
  'Sit through a quiet session without inventing a trade, and practice patience as an execution skill.',
  'Did my setup form, or did my patience run out?', [
    scene('Waiting Is the Work', '9:45', [
        say('9:45. Analysis done. You know what you’re waiting for.', 'Nothing has formed.'),
        ch(WAIT_PRE, head={'tf': '1M', 'label': '10:21 · still nothing'}),
        th('“This is so boring.”', '“Maybe that counts?”', '“Let me check the 30-second chart.”'),
        choice('10:21. What do you do?',
            op('Take the almost-setup', track=['boredomCount', 'emotionalTradesTaken'],
               chart=ch(WAIT_FORCE, play=(len(WAIT_PRE), len(WAIT_FORCE)), head={'tf': '1M', 'label': 'The almost-setup'}, tags=[{'at': len(WAIT_FORCE) - 1, 'text': '−1R', 'tone': 'warn'}]),
               say=['Indication only. It didn’t become anything.', 'Boredom doesn’t complete a setup.']),
            op('Drop to a smaller timeframe until something shows up', track=['boredomCount'],
               say=['On a small enough chart, you can always find “something”.', 'That isn’t finding a setup. <b>That’s searching for permission.</b>']),
            op('Keep waiting', track='patienceSuccessCount',
               chart=ch(WAIT_A, play=(len(WAIT_PRE), WAM['retest'] + 3), head={'tf': '1M', 'label': '10:31'}),
               say=['10:31. It formed. Indication, Correction, Continuation, first retest.', 'And some days it never does. <b>Then the waiting was the whole job, and you did it.</b>'])),
        cards('🎯 WHAT you’re waiting for', '🧭 WHY you’re waiting', '⏳ WHAT hasn’t happened yet', '✗ WHAT would cancel it', '🕒 WHEN your session ends'),
        who('THE TRADER', ['Knows what she’s waiting for.'], 'THE BOREDOM', ['Wants something to do.', 'Will find “something” on any chart.']),
        pr('WAITING FOR THE SETUP IS PART OF EXECUTING THE SETUP.'),
    ]),
    dayli('Some of my best sessions had zero trades. <em>They count.</em>'),
    reflect('What does active patience look like for you?',
            'I know what I’m waiting for, why, what hasn’t happened yet, what would cancel it and when my session ends. If nothing forms, the waiting was the job.'),
  ], ['Patience is an execution skill.', 'Boredom doesn’t complete a setup.', 'Did my setup form, or did my patience run out?'],
  'DID MY SETUP FORM… OR DID MY PATIENCE RUN OUT?', 85)

# ── 11 · The Trade You Need to Work ───────────────────────────────────
L[11] = lesson(P, S, 11, 'The Trade You Need to Work', 'When your bills get in the trade with you.',
  'Feel money pressure ride along in a trade, and keep the size and the stop where your plan put them.',
  'Am I trading the chart, or what I need from it?', [
    scene('The Trade You Need to Work', 'Thursday', [
        cards('EVAL RENEWAL · FRIDAY', 'RENT · THE 1ST', 'THIS WEEK · −3R'),
        say('None of that is on the chart.', '<b>All of it is in the trade with you.</b>'),
        ch(NEED, play=(NEED_E, NEED_GREEN + 2), **IN_TRADE(NEED, NEED_E)),
        say('Valid entry. +6. +11. Then it starts to slip.'),
        th('“This one HAS to work.”', '“If it stops out, I’m done for the month.”'),
        choice('It’s heading toward your stop. What do you do?',
            op('Move the stop lower so it can’t stop out', track=['fearDrivenManagementCount', 'emotionalTradesTaken'],
               chart=ch(NEED_WIDE, play=(NEED_GREEN + 2, len(NEED_WIDE)), pil=None, lines=trade_lines(NEED_E, stop_label='STOP −30 (moved)'), head={'tf': '1M', 'label': 'Long 2 MNQ'}),
               say=['It kept going.', 'The trade you needed to work cost <b>twice</b> what your plan allowed.'], tally=[['RESULT', '−2R', 'mind'], ['RULES BROKEN', '1 · stop moved', 'mind']]),
            op('Close it now. Save what’s left.', track='fearDrivenManagementCount',
               chart=ch(NEED_SL, play=(NEED_GREEN + 2, len(NEED_SL)), **IN_TRADE(NEED_SL, NEED_E)),
               say=['−0.3R instead of −1R. This time, closing early “worked”.', 'That’s exactly how it becomes a habit. <b>Next time it closes you out of a winner.</b>']),
            op('Leave it. The stop is the plan.', track='ruleBasedResponses',
               chart=ch(NEED_SL, play=(NEED_GREEN + 2, len(NEED_SL)), **IN_TRADE(NEED_SL, NEED_E)),
               say=['−1R. It didn’t work.', 'Your rent didn’t decide the outcome. <b>Your rules decided the size of it.</b>'], tally=[['RESULT', '−1R · valid', 'neutral'], ['RULES BROKEN', '0', 'ok']])),
        who('THE TRADER', ['Sized the trade for her account.'], 'THE PRESSURE', ['Needs this trade to pay a bill.', 'Will break any rule to protect it.']),
        say('If one trade decides your month, the size is too big for your situation right now.', 'That’s a review decision, made calmly. Not a live one.'),
        pr('THE MARKET DOESN’T KNOW WHAT YOU NEED.'),
    ]),
    dayli('If you can’t afford the loss, you can’t afford the trade. <em>Size for your life, not your hopes.</em>'),
    reflect('What pressure comes into the trade with you?',
            'Bills, an eval fee, a payout goal, a bad week. When I need a trade to work, I move stops, cut winners or size up. I size for what I can actually afford to lose.'),
  ], ['The market doesn’t know what you need.', 'Pressure moves stops. Rules keep them.', 'Size for your life, decided in review.'],
  'THE MARKET DOESN’T KNOW WHAT YOU NEED.', 85)

# ── 12 · You Are Not Your P&L ─────────────────────────────────────────
L[12] = lesson(P, S, 12, 'You Are Not Your P&L', 'A red day is not a verdict on you.',
  'Separate the outcome of a trade from the quality of your process, and both from your worth.',
  'Did I follow my process, whatever the result?', [
    scene('You Are Not Your P&L', 'Two trades. Same day.', [
        ch(HES, show=HM['continuation'], head={'tf': '1M', 'label': 'Trade A · you entered before Continuation closed'}, tags=[{'at': HM['continuation'] - 1, 'text': 'EARLY', 'tone': 'warn'}]),
        say('Trade A: you entered early. Continuation hadn’t closed.', 'It ran anyway. <b>+2R.</b>'),
        th('“I’m a genius.”'),
        ch(LOSS, head={'tf': '1M', 'label': 'Trade B · every rule followed'}, tags=[{'at': LM['retest'], 'text': 'FIRST RETEST', 'tone': 'gold'}, {'at': len(LOSS) - 1, 'text': '−1R', 'tone': 'warn'}]),
        say('Trade B: every rule followed. Stopped out. <b>−1R.</b>'),
        th('“I’m so bad at this.”'),
        choice('Which trade made you a better trader?',
            op('Trade A. It made money.', track='feelingAsReason',
               say=['It paid you for a habit that will cost you later.', 'A win from an early entry teaches you to enter early.']),
            op('Trade B. It followed the process.', track='ruleBasedResponses',
               say=['It cost you 1R and it’s the trade you want a hundred more of.', 'That’s what a model is: many of these, over time.'])),
        cards('OUTCOME · what happened to the money', 'PROCESS · what happened to the rules', 'YOU · neither one'),
        say('Your P&amp;L grades the trade. Your journal grades the process.', '<b>Neither one grades you.</b>'),
        pr('YOUR P&L IS INFORMATION ABOUT TRADES. IT ISN’T A VERDICT ABOUT YOU.'),
    ]),
    {'type': 'p7_process', 'kicker': 'Your journal, two columns', 'title': 'Grade it the way it actually happened',
     'trades': [{'name': 'TRADE A', 'facts': ['Entered before Continuation.', 'Closed at +2R.'], 'result': '+2R WIN', 'violations': ['Early entry'], 'answers': {'outcome': 'WIN', 'process': 'VIOLATION'}},
                {'name': 'TRADE B', 'facts': ['Every rule followed.', 'Stop hit.'], 'result': '−1R LOSS', 'answers': {'outcome': 'LOSS', 'process': 'FOLLOWED'}}]},
    dayli('Some of my best trades lost money. <em>Some of my worst ones paid me.</em>'),
    reflect('How do you talk to yourself after a red day?',
            'I want to separate it: what happened to the money, what happened to the rules, and me. A red day with every rule followed is a good day of process. It isn’t a verdict on who I am.'),
  ], ['Outcome and process are different columns.', 'A win can teach a bad habit.', 'Neither column grades you.'],
  'YOUR P&L IS INFORMATION ABOUT TRADES. IT ISN’T A VERDICT ABOUT YOU.', 85)

# ── 13 · Who's Trading Now? ───────────────────────────────────────────
L[13] = lesson(P, S, 13, 'Who’s Trading Now?', 'Before you read the chart, read you.',
  'Check your own state before a session, and catch who is making the decision in the moment.',
  'Who is trading right now: the trader, or the feeling?', [
    scene('Who’s Trading Now?', 'Three moments. One question.', [
        say('By now you’ve met them all.', 'The win. The heater. The loss. The streak. “I knew it.” Frozen. The candle you can’t stop watching. One more. Boredom. The bills.'),
        say('They don’t show up one at a time. <b>They show up in the middle of a normal Tuesday.</b>'),
        choice('9:58. You lost yesterday. A valid setup forms. Your stomach drops.',
            op('Notice it, check the rule, take it', track='ruleBasedResponses', say=['The feeling came along. <b>The trader made the decision.</b>']),
            op('Skip it. Not today.', track='hesitationCount', say=['That wasn’t a decision about this chart. <b>Yesterday made it.</b>'])),
        choice('10:20. +2R on the day. Your plan says done.',
            op('One more. You’re on.', track='overtradeCount', say=['The heater made that one.']),
            op('Done. Journal and close.', track='ruleBasedResponses', say=['The trader.'])),
        choice('10:41. You’re in a trade, +15, and a red candle prints.',
            op('Close it to protect the green', track='fearDrivenManagementCount', say=['Fear made that one. No rule triggered.']),
            op('Hold. Nothing in the plan changed.', track='ruleBasedResponses', say=['The trader.'])),
        say('Same person. Same morning. <b>Different traders, minute to minute.</b>', 'The skill isn’t never feeling it. It’s noticing who just took the mouse.'),
        pr('BEFORE EVERY CLICK: WHO’S TRADING NOW?'),
    ]),
    {'type': 'p7_temp', 'kicker': 'Your emotional temperature', 'title': 'Read you first',
     'body': 'Where would you put each thought? This is for noticing, not grading yourself.',
     'items': [{'thought': 'Ready. Plan’s clear.', 'state': 'calm'}, {'thought': 'Ooh, it’s moving fast.', 'state': 'elevated'},
               {'thought': 'Ugh. Third loss this week.', 'state': 'frustrated'}, {'thought': 'I NEED that back. Now.', 'state': 'red'}],
     'punch': 'A red state doesn’t make the setup invalid. It makes your personal rules matter more. (That’s Section 2.)'},
    {'type': 'p7_state_card', 'kicker': 'Trader State Card', 'title': 'Write the state down, not just the trade',
     'example': {'emotion': 'Frustrated', 'intensity': 'High', 'trigger': 'Previous valid loss', 'urge': 'Take the next setup early', 'ruleAtRisk': 'Wait for Continuation', 'plannedResponse': 'Pause and require the full checklist'},
     'own': True, 'punch': 'Private to you. Never shared, never ranked.'},
    dayli('I check my chart before every session. <em>I check myself first.</em>'),
    reflect('Which version of you shows up most often, and when?',
            'I notice which feeling shows up and when: after a loss, after a win, when I’m bored, when money is tight. Before every click I ask who is trading right now.'),
  ], ['Different traders, minute to minute.', 'Read yourself before the chart.', 'Before every click: who’s trading now?'],
  'BEFORE EVERY CLICK: WHO’S TRADING NOW?', 85)

if __name__ == '__main__':
    for n, d in L.items():
        chk(d)
        write(f'p7-{n}.json', d)
